name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: &runner ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install norminette
      run: python3 -m pip install -U norminette
  check:
    runs-on: *runner
    steps:
    - uses: actions/checkout@v4
    - name: Check norminette
      run: norminette ./srcs ./includes
