name: Norminette

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install norminette
        run: python3 -m pip install -U norminette
      - name: Run norminette
        run: python3 -m norminette ./srcs ./includes
